### PR TITLE
Check that `target_id`s match `target_key` values

### LINKED ISSUE #102: validate that `target_id` matches the values of `target_keys`
The [flu metrocast hub](https://github.com/reichlab/flu-metrocast) has two targets, ILI ED visits and Flu ED visits pct. 

The target metadata for the first key looks like this:

```json
                    "target_metadata": [
                        {
                            "target_id": "ili-ed-visits",
                            "target_name": "ED visits due to ILI",
                            "target_units": "count",
                            "target_keys": {
                                "target": "ILI ED visits"
                            },
                            "target_type": "continuous",
                            "description": "This target represents the count of ED visits due to ILI in the week ending on the date [horizon] weeks after the reference_date, on the target_end_date.",
                            "is_step_ahead": true,
                            "time_unit": "week"
                        }
                    ]
```

I did not notice any problem until I attempted to run the evaluations on the data: 

```
! Error in predevals config file:
Target id "ILI ED visits" not found in any task group.
Backtrace:
    ▆
 1. └─hubPredEvalsData::generate_eval_data(...)
 2.   └─hubPredEvalsData:::read_config(hub_path, config_path) at hubPredEvalsData/R/generate_eval_data.R:14:3
 3.     └─hubPredEvalsData:::validate_config(hub_path, config) at hubPredEvalsData/R/config.R:24:3
 4.       └─hubPredEvalsData:::validate_config_vs_hub_tasks(hub_path, config) at hubPredEvalsData/R/config.R:34:3
 5.         └─hubPredEvalsData:::validate_config_targets(...) at hubPredEvalsData/R/config.R:165:3
 6.           └─hubPredEvalsData:::raise_config_error(cli::format_inline("Target id {.val {target_id}} not found in any task group.")) at hubPredEvalsData/R/config.R:190:7
 7.             └─cli::cli_abort(c("Error in predevals config file:", msgs)) at hubPredEvalsData/R/config.R:380:3
 8.               └─rlang::abort(...) at cli/R/rlang.R:45:3
```

It turned out that `target_id` and `target_keys/target` were not equal, but the validation did not fail. I'm not quite sure how to do it, but it would be a good idea to make sure these values are identical. 

related PR fixing the issue: https://github.com/reichlab/flu-metrocast/pull/58

### PR DESCRIPTION
**Pull request by annakrystalli**
This PR resolves #102  by validating that `target_id` `target_metadata` item properties match the corresponding `target_key` value.

Note that this check is not implemented if the `target_key`s are `NULL` or when the length of `target_key`s property does not equal the length of the `target_id`(which is always 1L. This is to account for earlier schema versions where target keys were allowed to be spread across multiple task IDs. Because this complicates this check, it is just skipped in when the length of target key values is not 1L.

Note as well that we already have checks that ensure target keys are valid target task ID values . Consequently, the addition of this new check also ensures `target_id`s represent valid target task ID values.

### CODE REVIEW

File: tests/testthat/test-create_target_metadata.R [hunk 1]
```diff
@@ -62,7 +62,7 @@ test_that("create_target_metadata functions error correctly", {
         time_unit = "week"
       ),
       create_target_metadata_item(
-        target_id = "inc death",
+        target_id = "inc hosp",
```
Comment (annakrystalli) [inline tests/testthat/test-create_target_metadata.R:65]: This change is to ensure the old test was actually testing what it was originally designed to, i.e. the presence of duplicate `target_id`/`target_key` values in a `target_metadata` block. The added check meant it was now detecting the target_id/target_key` value mismatch instead of the duplicate target_keys. I changed it so the target_id now matches the target_keys and it is now successfully picking up the duplicate `target_id`s first.

File: tests/testthat/test-create_target_metadata.R [hunk 2]
```diff
@@ -113,7 +113,7 @@ test_that("create_target_metadata functions error correctly", {
             target_id = "inc death",
             target_name = "Weekly incident influenza deaths",
             target_units = "rate per 100,000 population",
-            target_keys = list(target = "inc hosp"),
+            target_keys = list(target = "inc death"),
```
Comment (annakrystalli) [inline tests/testthat/test-create_target_metadata.R:116]: As above

File: tests/testthat/_snaps/create_target_metadata.md [hunk 3]
```diff
@@ -92,13 +92,13 @@
...
         is_step_ahead = TRUE, time_unit = "week"), create_target_metadata_item(
-        target_id = "inc death", target_name = "Weekly incident influenza deaths",
+        target_id = "inc hosp", target_name = "Weekly incident influenza deaths",
         target_units = "rate per 100,000 population", target_keys = list(target = "inc hosp"),
         target_type = "discrete", is_step_ahead = TRUE, time_unit = "week"))
     Condition
       Error in `create_target_metadata()`:
-      ! `target_keys`s must be unique across all `target_metadata_item`s.
-      x `target_metadata_item` 2 with `target_keys` value list(target = "inc hosp") is duplicate.
+      ! `target_id`s must be unique across all `target_metadata_item`s.
```
[the remark this answers is not in the document]
Comment (zkamvar) [reply tests/testthat/_snaps/create_target_metadata.md:100]: Thank you for the context! I really appreciate it.

**Review by zkamvar — APPROVED** [review]
This looks great, Thank you! 

I was low-key wondering how one would go about this and this is a really good example of how we can add checks that are not possible by the limitations of JSON schema.

**Comment by annakrystalli** [comment]
> I was low-key wondering how one would go about this and this is a really good example of how we can add checks that are not possible by the limitations of JSON schema.

Yeah I had an epiphany this morning! 😜
