### PR TITLE
Use options to set `schema_version` and `branch`

### LINKED ISSUE #85: use an option for schema version for create functions
In [reichlab/variant-nowcast-hub#176](https://github.com/reichlab/variant-nowcast-hub/pull/176/files#diff-3361d89a46e263279543b41cee56a8c99852d1f2052dd4bfe295d54842d57fdb), the workflow to create a new round began to fail because the default schema for functions like `create_task_id` is "latest" so it constructed a v4 schema instead of v3.0.1 resulting in the following error:

```
ℹ Existing config found, adding a new round
Error in `hubAdmin::append_round()`:
✖ Schema version mismatch between `config` and round.
! Must be the same.
• `config`:
  "https://raw.githubusercontent.com/hubverse-org/schemas/main/v3.0.1/tasks-schema.json"
• round:
  "https://raw.githubusercontent.com/hubverse-org/schemas/main/v4.0.0/tasks-schema.json"
Backtrace:
    ▆
 1. └─hubAdmin::append_round(existing_task_config, new_round)
 2.   └─cli::cli_abort(...) at hubAdmin/R/append_round.R:133:5
 3.     └─rlang::abort(...)
```

I think we should specify `schema = getOption("hubAdmin.schema_version", default = "latest")` in the function signatures, so that way users can specify one line at the top of their script to set the schema version while they are developing the script. 

```r
options(hubAdmin.schema_version = "v3.0.1")
```

### PR DESCRIPTION
**Pull request by annakrystalli**
This PR resolves #85 by setting the default values of `schema_version` and `branch` arguments to be set by options, with appropriate default values. Specifically:
- `schema_version` is set by `hubAdmin.schema_version` option
- `branch` is set by `hubAdmin.branch` option

I also added examples of how to set them. I thought about using `withr::with_options()` to temporarily set the options but I didn't as it wasn't the approach an actual user would use. So I ended up resetting the options at the end of each example block. Happy for suggestions of demonstrating this in a better way.

### Miscellaneous
- I also remove a couple of instances where `mockery::stub()` was being used and went ahead and removed all instances of tests which were configured against the `br-v4.0.0` branch, resolving #71

### CODE REVIEW

File: tests/testthat/test-create_task_id.R
Comment (zkamvar) [inline tests/testthat/test-create_task_id.R:1]: there needs to be one more `askYesNo` mock after line 68 (when I run `devtools::test()`, it hangs here waiting for me to give it validation).

File: DESCRIPTION [hunk 1]
```diff
@@ -44,7 +44,6 @@ Suggests:
     hubData,
     knitr,
     withr,
-    mockery,
```
Comment (zkamvar) [inline DESCRIPTION:47]: 🔥 🔥 🔥 BURN IT DOWN!

**Review by zkamvar — CHANGES_REQUESTED** [review]
Thank you! LGTM. There's one minor thing to include one more mocking of `askYesNo()` after line 68 of the test file.

File: tests/testthat/test-create_task_id.R
Comment (annakrystalli) [reply tests/testthat/test-create_task_id.R:1]: Hmm that's strange because the tests all run successfully when using the test button on the build panel as well as CI. `devtools::test()` also seems to be affected by the global environment when running. For example it seemed to be setting the `hubAdmin.schema_version` somewhere globally which was leaking into other tests (and lingered into the global environment afterwards) which does not happen when clicking the test button on the build panel or on CI. So not sure it's the best choice for running tests (see also note about [discrepancies in results in test results via `devtools::test()` and `R CMD CHECK`](https://r-pkgs.org/R-CMD-check.html#tests) in the R packages book). I've made changes in any case in da4e4cbbce135fbe7d967daaee64dd441e8045eb  so both pass but I think if it passes on CI it should be ok no?

Comment (zkamvar) [reply tests/testthat/test-create_task_id.R:1]: > Hmm that's strange because the tests all run successfully when using the test button on the build panel as well as CI.

Ahhhh that's because RStudio does not run this in your default environment. The interactive element is what caught me up because `askYesNo` will return the default `TRUE` when called in a non-interactive environment:

``` r
callr::r(function() askYesNo("what"))
#> [1] TRUE
```

<sup>Created on 2024-12-04 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>


> I think if it passes on CI it should be ok no?

Kind of... this particular test was implicitly testing the default response, but the mock makes the test explicit and easier to reason about.

Comment (zkamvar) [reply tests/testthat/test-create_task_id.R:1]: Nevertheless, I really appreciate the fix!

**Review by zkamvar — APPROVED** [review]
